# Generated by Django 3.2.9 on 2021-12-03 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
    ]
